cvm-version: 0.11.0
shim:
  upstream-container: router
  upstream-port: 8089
  paths:
  - /v1/chat/completions
  - /v1/completions
  - /v1/embeddings
  - /v1/models
  - /health
  - /metrics
  dummy-attestation: false
  publish-attestation: false
  authenticated: true
  authenticated-endpoints:
  - /v1/chat/completions
  - /v1/completions
  - /v1/embeddings
  - /v1/models
  tls-mode: cert-proxy
  tls-challenge: dns
  tls-own-san-domain: true
  control-plane: https://api.inference.aptoslabs.com/
cvm-network:
  inbound-ports:
  - 443
networks:
  router-egress:
    egress: allowlist
    allow:
    - raw.githubusercontent.com
    - github-proxy.tinfoil.sh
    - tuf-repo-cdn.sigstore.dev
    - api.inference.aptoslabs.com
    - host0.inference.aptoslabs.com
    - glm0-internal.inference.aptoslabs.com
cpus: 8
memory: 16384
gpus: 0
models: []
containers:
- name: router
  image: ghcr.io/tinfoilsh/confidential-model-router@sha256:c51e12746b17479692daabdf00608d30d682c300b0ed9fee57c50fca1b4f5ba4
  ipc: private
  restart: always
  networks:
  - router-egress
  command:
  - -l=8089
  - -C=https://api.inference.aptoslabs.com/
  - -usage-reporter-id=model-router
  - -i=https://raw.githubusercontent.com/aptos-labs/confidential-inference-router/v0.0.2/config.yml@sha256:30f714d1b5b7532700df670d65fc5289270b8c527226755ddee2606c93ea8949
  - -u=https://raw.githubusercontent.com/aptos-labs/confidential-inference-router/v0.0.2/config.yml@sha256:30f714d1b5b7532700df670d65fc5289270b8c527226755ddee2606c93ea8949
  - -d=router.inference.aptoslabs.com
  secrets:
  - USAGE_REPORTER_SECRET
  - USAGE_CONTEXT_SECRET
  - INFERENCE_DELEGATION_SECRET
  healthcheck:
    test:
    - CMD
    - wget
    - -q
    - --spider
    - http://localhost:8089/health
    interval: 30s
    timeout: 10s
    start_period: 5m
  tmpfs:
    /tmp: size=256m,mode=1777,exec
