cvm-version: 0.11.0
shim:
  upstream-container: router
  upstream-port: 8089
  paths:
  - /v1/chat/completions
  - /v1/completions
  - /v1/embeddings
  - /v1/models
  - /v1/videos/sync
  - /health
  - /metrics
  dummy-attestation: false
  publish-attestation: false
  authenticated: true
  authenticated-endpoints:
  - /v1/chat/completions
  - /v1/completions
  - /v1/embeddings
  - /v1/models
  - /v1/videos/sync
  tls-mode: cert-proxy
  tls-challenge: dns
  tls-own-san-domain: true
  control-plane: https://api.inference.aptoslabs.com/
cvm-network:
  inbound-ports:
  - 443
networks:
  router-egress:
    egress: allowlist
    allow:
    - raw.githubusercontent.com
    - github-proxy.tinfoil.sh
    - tuf-repo-cdn.sigstore.dev
    - api.inference.aptoslabs.com
    - host0.inference.aptoslabs.com
    - host1.inference.aptoslabs.com
cpus: 8
memory: 16384
gpus: 0
models: []
containers:
- name: router
  image: ghcr.io/aptos-labs/confidential-model-router@sha256:a2f7cf1e50b6b440f58ce04d3f4d85d04e7b25d27325cc83f9e3fb181e105d90
  ipc: private
  restart: always
  networks:
  - router-egress
  command:
  - -l=8089
  - -C=https://api.inference.aptoslabs.com/
  - -usage-reporter-id=model-router
  - -i=https://raw.githubusercontent.com/aptos-labs/confidential-inference-router/v0.0.5/config.yml@sha256:493b9ca39b3385fc2a2099fa6bb443f973b66356a945e8caff731d7366a568bf
  - -u=https://raw.githubusercontent.com/aptos-labs/confidential-inference-router/v0.0.5/config.yml@sha256:493b9ca39b3385fc2a2099fa6bb443f973b66356a945e8caff731d7366a568bf
  - -d=router.inference.aptoslabs.com
  secrets:
  - USAGE_REPORTER_SECRET
  - USAGE_CONTEXT_SECRET
  - INFERENCE_DELEGATION_SECRET
  healthcheck:
    test:
    - CMD
    - wget
    - -q
    - --spider
    - http://localhost:8089/health
    interval: 30s
    timeout: 10s
    start_period: 5m
  tmpfs:
    /tmp: size=256m,mode=1777,exec
